---
fixtures:
  repositories:
    dynatrace: 'https://github.com/Dynatrace/Dynatrace-Puppet.git'
  forge_modules:
    #dynatrace: 'dynatrace/dynatrace'
    apache: 'puppetlabs/apache'
    java: 'puppetlabs/java'
    stdlib: 'puppetlabs/stdlib'
    dirtree: 'AlexCline/dirtree'
    wget: 'maestrodev/wget'
  symlinks:
    profile: "#{source_dir}"
